### PR TITLE
Vpr and refactor

### PR DESCRIPTION
**Pull request by Tyndareus**
Feel free to scrutinize the viper changes, its less than what I showed originally.

Mainly here to get eyes on the refactor, but if it is well received feel free to keep. It makes it a lot easier to just have people edit the jobs individually rather than all pile into IconReplacer...

The CustomComboPreset needs to be addressed, I will look at it afterwards... I had a quick poke with using a custom bit array wrapper but theres a serialization issue with dalamud

I remade the PR because I remade my fork

### CODE REVIEW

**Comment by Tyndareus** [comment]
Ok so I have a change involving the CustomComboPreset, but it'd require people to reselect the options because of how the config is saved for previous settings. It would allow int max number of combos so is future proof... 
I will have a dig around to see if I can pull the old combo presets value from the saved plugin config and do some form of upgrade

Edit: couldn't do the upgrade as the numbers didn't align correctly

**Comment by Skooz** [comment]
I'll give this a good looking over when I get the chance.

Lots of sweeping changes here, and they're good, but I don't plan on taking over development indefinitely or anything, so I'm not sure how much future proofing we need on my fork, lol. Though I'll still try to get them merged when I can, since it wouldn't do any harm.

I think if I continue development on my own version of the plugin, I'll probably start from scratch, or just use a different base. I like Sloth's new UI, but the focus on one-button-rotations and some other bizarrely implemented combo options always threw me off using it too much.

**Comment by Tyndareus** [comment]
New plan on this whole thing then?

**Comment by Skooz** [comment]
Auto closed since I'm changing branches around. But, like I said, I don't think I plan to continue my "version", especially now that attick is back to updating the main repo; I'd rather help out with that for the time being.

**Comment by Tyndareus** [comment]
Ah alright, I will either maintain my local version or open it up with attick

**Pull request closed without merging**
